apiVersion: v1
kind: ConfigMap
metadata:
  name: eg-config
data:
  DB_HOST: postgresql-db-service
  DB_PORT: "5432"
  DB_USERNAME: postgres
  AUTH_SERVICE_HOST: auth-svc
  ORDER_SERVICE_HOST: order-svc
  PRODUCT_SERVICE_HOST: product-svc
