apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
        version: v1
    spec:
      containers:
      - name: auth
        image: auth-service:1
        envFrom:
          - configMapRef:
              name: eg-config
          - secretRef:
              name: eg-secrets
        resources:
          limits:
            memory: "528Mi"
            cpu: "0.5"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-svc
spec:
  selector:
    app: auth
  ports:
  - port: 50051
    name: grpc
    protocol: TCP 
  
