apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
        version: v1
    spec:
      containers:
      - name: product-service
        image: product-service:1
        envFrom:
          - configMapRef:
              name: eg-config
          - secretRef:
              name: eg-secrets
        resources:
          limits:
            memory: "528Mi"
            cpu: "0.3"
---
apiVersion: v1
kind: Service
metadata:
  name: product-svc
spec:
  selector:
    app: product-service
  ports:
  - port: 50053
    name: grpc
    protocol: TCP 
  
